on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
name: "Build and upload release"
concurrency:
  group: "${{ github.repository }}-${{ github.workflow }}"
jobs:
  build:
    uses: baerchen201/LethalModBuilder/.github/workflows/build.yml@main
    permissions:
      contents: write
