on:
  push:
    branches: # Continuous releases
      - main
    tags: # Version releases
      - "*"
  workflow_dispatch:
name: "Build and upload release"
concurrency:
  group: "${{ github.repository }}-${{ github.workflow }}"
jobs:
  build:
    uses: baerchen201/LethalModBuilder/.github/workflows/build.yml@main
    permissions:
      contents: write
    with:
      prerelease: ${{ github.ref_type == 'tag' }}
